# Generated by Django 5.0.3 on 2024-03-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=20)),
                ("address", models.TextField()),
                (
                    "pic",
                    models.FileField(
                        default=None,
                        max_length=250,
                        null=True,
                        upload_to="profile_pic/",
                    ),
                ),
            ],
        ),
    ]
