# Generated by Django 5.0.3 on 2024-03-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pic",
            field=models.ImageField(
                default=None, max_length=250, null=True, upload_to="profile_pic/"
            ),
        ),
    ]
