# Generated by Django 5.0.3 on 2024-03-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0003_alter_user_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_auth",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(default="Client", max_length=10),
        ),
    ]
