# Generated by Django 5.0.3 on 2024-03-25 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0004_user_user_auth_user_user_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="product_carsoule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("details", models.TextField(max_length=250)),
                ("product_price", models.FloatField(default=50)),
                ("product_type", models.CharField(max_length=20)),
                (
                    "product_added_time",
                    models.TimeField(
                        default=datetime.datetime(2024, 3, 25, 15, 9, 55, 887370)
                    ),
                ),
                (
                    "product_offers",
                    models.CharField(
                        default="No Offers For Now", max_length=150, null=True
                    ),
                ),
                ("pic", models.FileField(max_length=250, upload_to="carsoul_product")),
            ],
        ),
    ]
