# Generated by Django 5.0.3 on 2024-03-25 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0007_alter_product_carsoule_pic_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("details", models.TextField(max_length=250)),
                ("product_price", models.FloatField(default=50)),
                ("product_type", models.CharField(max_length=20)),
                (
                    "product_added_time",
                    models.TimeField(
                        default=datetime.datetime(2024, 3, 25, 16, 51, 2, 360668)
                    ),
                ),
                (
                    "product_offers",
                    models.CharField(
                        default="No Offers For Now", max_length=150, null=True
                    ),
                ),
                (
                    "pic",
                    models.FileField(
                        max_length=250, upload_to="carsoul_product/{{name}}"
                    ),
                ),
                (
                    "pic2",
                    models.FileField(
                        max_length=250, null=True, upload_to="carsoul_product/{{name}}"
                    ),
                ),
                (
                    "pic3",
                    models.FileField(
                        max_length=250, null=True, upload_to="carsoul_product/{{name}}"
                    ),
                ),
                (
                    "pic4",
                    models.FileField(
                        max_length=250, null=True, upload_to="carsoul_product/{{name}}"
                    ),
                ),
                (
                    "pic5",
                    models.FileField(
                        max_length=250, null=True, upload_to="carsoul_product/{{name}}"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="product_carsoule",
        ),
    ]
