# Generated by Django 5.0.3 on 2024-03-25 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0009_alter_product_pic_alter_product_product_added_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="pic",
            field=models.FileField(max_length=250, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic2",
            field=models.FileField(max_length=250, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic3",
            field=models.FileField(max_length=250, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic4",
            field=models.FileField(max_length=250, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pic5",
            field=models.FileField(max_length=250, null=True, upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_added_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 3, 25, 17, 28, 26, 696905)
            ),
        ),
    ]
