# Generated by Django 5.0.3 on 2024-03-25 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0010_alter_product_pic_alter_product_pic2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_added_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 3, 25, 17, 37, 20, 877496)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_offers",
            field=models.CharField(default="No Offers For Now", max_length=150),
        ),
    ]
