# Generated by Django 5.0.3 on 2024-03-25 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0012_alter_product_product_added_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="edoc",
            field=models.FileField(
                default=None, max_length=350, upload_to="downloadable/"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="product_added_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 3, 25, 17, 52, 26, 167025)
            ),
        ),
    ]
