# Generated by Django 5.0.3 on 2024-03-25 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0015_alter_product_product_added_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_added_time",
            field=models.TimeField(
                default=datetime.datetime(2024, 3, 26, 0, 48, 41, 806566)
            ),
        ),
    ]
