# Generated by Django 5.0.3 on 2024-03-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0017_user_user_code_alter_product_product_added_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_added_time",
            field=models.TimeField(default="2024-03-29 14:06:15"),
        ),
    ]
