# Generated by Django 5.0.3 on 2024-03-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0018_alter_product_product_added_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_added_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
