# Generated by Django 5.0.3 on 2024-03-29 13:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0020_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="order",
        ),
    ]
