# Generated by Django 5.0.3 on 2024-03-29 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0021_delete_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("umail", models.EmailField(max_length=254)),
                ("order_name", models.CharField(max_length=30)),
                ("order_details", models.TextField(default="No Details")),
                ("ex_order_delevery", models.DateField()),
                ("ex_order_delevery_time", models.TimeField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.user"
                    ),
                ),
            ],
        ),
    ]
