# Generated by Django 5.0.3 on 2024-03-30 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0022_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="order",
            new_name="ordered",
        ),
    ]
