# Generated by Django 5.0.3 on 2024-03-31 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0025_delete_cart"),
    ]

    operations = [
        migrations.CreateModel(
            name="reportProblem_1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("umail", models.EmailField(max_length=254)),
                ("report_title", models.TextField()),
                ("explain", models.TextField()),
                ("problem_date", models.DateField()),
                ("problrm_time", models.TimeField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="reportProblem_2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mmail", models.EmailField(max_length=254)),
                ("report_title", models.TextField()),
                ("explain", models.TextField()),
                ("problem_date", models.DateField()),
                ("problrm_time", models.TimeField()),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "mid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.user"
                    ),
                ),
            ],
        ),
    ]
