# Generated by Django 5.0.3 on 2024-03-31 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0029_rename_problrm_time_reportproblem_1_problem_time_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="reportProblem_2",
        ),
    ]
