# Generated by Django 5.0.3 on 2024-03-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0030_delete_reportproblem_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordered",
            name="ex_order_delevery",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="ordered",
            name="ex_order_delevery_time",
            field=models.TimeField(null=True),
        ),
    ]
