# Generated by Django 5.0.3 on 2024-03-31 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0031_alter_ordered_ex_order_delevery_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportproblem_1",
            name="explain",
        ),
        migrations.RemoveField(
            model_name="reportproblem_1",
            name="problem_date",
        ),
        migrations.RemoveField(
            model_name="reportproblem_1",
            name="problem_pic",
        ),
        migrations.RemoveField(
            model_name="reportproblem_1",
            name="problem_time",
        ),
        migrations.RemoveField(
            model_name="reportproblem_1",
            name="report_date",
        ),
        migrations.RemoveField(
            model_name="reportproblem_1",
            name="report_title",
        ),
    ]
