# Generated by Django 5.0.3 on 2024-03-31 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0032_remove_reportproblem_1_explain_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="reportProblem_1",
        ),
    ]
