# Generated by Django 5.0.3 on 2024-03-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0034_reportproblem_1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportproblem_1",
            name="problem_pic",
            field=models.FileField(max_length=250, null=True, upload_to="problems/"),
        ),
    ]
