# Generated by Django 5.0.3 on 2024-05-12 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0035_alter_reportproblem_1_problem_pic"),
    ]

    operations = [
        migrations.CreateModel(
            name="updated_last_profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Users.user"
                    ),
                ),
            ],
        ),
    ]
